config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :cafes do
    collection do
      get 'search'
    end
    resources :reviews, except: [:show, :index]
  end

  root 'home#index'

  get 'home/profile'

  get 'auth/:provider/callback', to: 'sessions#create'
  delete 'sign_out', to: 'sessions#destroy', as: 'sign_out'

  get 'cafes/search', to: 'cafes#search'
end

app/models/cafe.rb
class Cafe < ActiveRecord::Base
  # searchkick
  
  belongs_to :user
  has_many :reviews

  accepts_nested_attributes_for :reviews, reject_if: :all_blank, allow_destroy: true
end

app/models/review.rb
class Review < ActiveRecord::Base
  belongs_to :cafe
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :cafes
  has_many :reviews, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_filter :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << :name
    devise_parameter_sanitizer.for(:account_update) << :name
  end

end

app/controllers/cafes_controller.rb
class CafesController < ApplicationController
  before_action :set_cafe, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]

  def search
    render json: Cafe.all.select(:lat, :lng, :name).to_json
  end

  def index
    @cafes = Cafe.all.order("created_at DESC")
  end

  def show
  end

  def new
    @cafe = current_user.cafes.build
  end

  def create
    @cafe = current_user.cafes.build(cafe_params)

    if @cafe.save
      redirect_to @cafe
    else
      render 'new'
    end
  end

  def edit
  end

  def update
  end

  def destroy
  end

  private
    def set_cafe
      @cafe = Cafe.find(params[:id])
    end

    def cafe_params
      params.require(:cafe).permit(:name, :contact, :address, :lat, :lng, review_attributes: [:title, :comment, :rating])
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @cafes = Cafe.all.order("created_at DESC")
  end

  def profile
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_review, only: [:show, :edit, :update, :destroy]
  before_action :set_cafe  
  before_action :authenticate_user!

  def new
    @review = Review.new
  end

  def edit
  end

  def create
    @review = Review.new(review_params)
    @review.user_id = current_user.id
    @review.cafe_id = @cafe.id

    if @review.save
      redirect_to @cafe
    else
      render 'new'
    end
  end

  def update
    @review.update(review_params)
  end

  def destroy
    @review.destroy
    redirect_to root_path
  end

  private
    def set_review
      @review = Review.find(params[:id])
    end

    def set_cafe
      @cafe = Cafe.find(params[:cafe_id])
    end

    def review_params
      params.require(:review).permit(:title, :comment)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    auth = request.env["omniauth.auth"]
    session[:omniauth] = auth.except 'extra'
    user = User.sign_in_from_omniauth auth
    session[:user_id] = user.id
    redirect_to root_url, notice: "SIGNED IN"
  end

  def destroy
    session[:user_id] = nil
    session[:omniauth] = nil
    redirect_to root_url, notice: "SIGNED OUT"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/cafes/_form.html.slim
#cafe-form
  = simple_form_for @cafe, html: { id: :cafe_form } do |f|
    fieldset.cafe-form-fields
      = f.input :name
      = f.input :contact
      = f.button :submit, class: "btn btn-default"

app/views/cafes/edit.html.slim
h2 Edit Cafe

=render "form"

app/views/cafes/index.html.slim
h2 Cafes in Klang Valley

- @cafes.each do |cafe|
  p = cafe.name
  p = cafe.contact
  hr

button =link_to "Back to Home", root_path

app/views/cafes/new.html.slim
h2 Add New Cafe

=render "form"

app/views/cafes/show.html.slim
h2 = @cafe.name
p = @cafe.contact

div.map
  p map

= link_to "Write a review", new_cafe_review_path(@cafe)

button= link_to "Go Back to Home", root_path

app/views/home/index.html.slim
- if user_signed_in?
  ul.nav.navbar-nav.navbar-right
    li= link_to "Add New Cafe", new_cafe_path
    li= link_to "Sign Out", destroy_user_session_path, method: :delete
- else
  ul.nav.navbar-nav.navbar-right
    li= link_to "Sign Up", new_user_registration_path
    li= link_to "Sign In", new_user_session_path

#gmap.gmap
input#searchbox type="text"

.cafe-holder
  - @cafes.each do |cafe|
    p = cafe.name
    p = cafe.contact

app/views/home/profile.html.slim
h1 Home#profile
p Find me in app/views/home/profile.html.slim

app/views/layouts/application.html.slim
doctype html
html
  head
    title Hot Chocolate Review
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = csrf_meta_tags

  body
    = render "refills/navigation"
      
    .container
      - flash.each do |name, msg|
        = content_tag :div, msg, class: "alert"

      = yield

app/views/refills/_navigation.html.slim
header.navigation role="banner"
  .navigation-wrapper
    =link_to image_tag('https://raw.githubusercontent.com/thoughtbot/refills/master/source/images/placeholder_logo_1.png'), root_path, class: "logo"
    a#js-mobile-menu.navigation-menu-button
      MENU

    nav role="navigation"
      ul#js-navigation-menu.navigation-menu.show
        / -if current_user
        /   li.nav-link= link_to "Sign Out", "/sign_out", method: :delete
        / -else
        /   li.nav-link= link_to "Sign In", "/auth/facebook"
    .navigation-tools
      -if current_user
        p = current_user.email
      = render "refills/search_bar"

app/views/refills/_search_bar.html.slim
form.search-bar role= "search"
  input type="search" placeholder= "Enter Search"
  button type="submit"
    span
      i.fa.fa-search

app/views/reviews/_form.html.slim
#review-form
  = form_for([@cafe, @review]) do |f|
    fieldset.cafe-form-fields
      / = f.input :title
      = f.text_area :comment
      = f.button :submit, class: "btn btn-default"

app/views/reviews/edit.html.slim
h2 edit.html.slim

app/views/reviews/new.html.slim
h2 New Review

= render 'form'